# Arrays 

In [1]:
import numpy as np

In [2]:
a = np.array([1,45,78,90,100])

In [3]:
print (a)

[  1  45  78  90 100]


In [4]:
x = [45,56,15,58]
y = np.array(x)
print (y)
y #prints the type ;array
print (type(y))
print (y.ndim) #to find the dimension of the array given 

[45 56 15 58]
<class 'numpy.ndarray'>
1


In [5]:
l = [] #creating an empty list 

for i in range (1,5):
    int_1 = int(input("Enter the no. : "))
    l.append(int_1)

print (l)
print (np.array(l))
print (type(l))

Enter the no. :  89
Enter the no. :  56
Enter the no. :  36
Enter the no. :  25


[89, 56, 36, 25]
[89 56 36 25]
<class 'list'>


### 1 - D array -> [45,67]
### 2 - D array -> [[45,67], [89,90]]
### 3 - D array -> [[[67,78], [78,90], [98,90],]] 
### Higher dimension array 

## *Remember that the no. of elements in each block should be same.

# 2 - D

In [11]:
ar2 = np.array([[67,89,75,98], [87,98,78,65]]) #in 2-D, only two 1-D arrays are allowed 
print (ar2)
print (ar2.ndim)

[[67 89 75 98]
 [87 98 78 65]]
2


# 3 - D

In [12]:
ar3 = np.array([[[56,89], [90,89], [87,87]]])
print (ar3)
print (type (ar3))
print (ar3.ndim)

[[[56 89]
  [90 89]
  [87 87]]]
<class 'numpy.ndarray'>
3


# Creating n - dimension array 

In [15]:
arn = np.array ([67,90,69,69], ndmin=20) # "ndmin" to create our desired dimensioned array 
print (arn)
print (arn.ndim)

[[[[[[[[[[[[[[[[[[[[67 90 69 69]]]]]]]]]]]]]]]]]]]]
20
