# Zeroes

In [1]:
import numpy as np

In [2]:
ar_zeroes = np.zeros(4)
ar_zeroes1 = np.zeros((3,8)) #prints 3 X 4 matrix

print (ar_zeroes)
print ()
print (ar_zeroes1)

[0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# Ones 

In [3]:
ar_one = np.ones(7)
print (ar_one)

[1. 1. 1. 1. 1. 1. 1.]


In [12]:
ar_one1 = np.ones((3,8))
print (ar_one1)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# Empty

In [13]:
ar_empty = np.empty((3,8))

print (ar_empty)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#Prints the last array created

# Range

In [14]:
ar_range = np.arange(1,9)
ar_range1 = np.arange(9)

print (ar_range)
print (ar_range1)

[1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


# Diagonal filled with 1

In [7]:
ar_dia = np.eye(8) #prints the square matrix of the given attribute
ar_dia1 = np.eye(3,8) #prints the matrix of 3 rows and 8 columns

print (ar_dia)
print ()
print (ar_dia1)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


# Linspace

In [15]:
ar_lin = np.linspace(1,49,5) #starts from 1, till 49, with the gap of 5
ar_lin1 = np.linspace(0,100,10)

print (ar_lin)
print (ar_lin1)

[ 1. 13. 25. 37. 49.]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
