# Random 

## rand()

In [5]:
import numpy as np

var = np.random.rand(9) #random no.s between 0 and 1
var1 = np.random.rand(3,4) #random no.s between 0 and 1

print (var)
print ()
print (var1)

[0.0063385  0.9275661  0.39246737 0.24926171 0.59245571 0.66931768
 0.14922864 0.00352161 0.3530397 ]

[[0.28168868 0.26647881 0.72898003 0.61213136]
 [0.46669717 0.09265191 0.08771457 0.38195509]
 [0.52058402 0.52952883 0.12305972 0.57207376]]


## randn()
prints the no.s close to 0 (negative values allowed too)

In [6]:
var2 = np.random.randn(5)
var3 = np.random.randn(3,4)

print (var2)
print ()
print (var3)

[ 0.22823836  0.29797727 -0.95912992  1.91514492  0.02005341]

[[-1.50498429  0.20123467  1.35863683  2.32822337]
 [-1.46473274  1.2692415  -2.21316919 -0.11184027]
 [-0.53803226 -0.20346367  1.93388947  1.09077454]]


## ranf()

In [7]:
var4 = np.random.ranf(5)

print (var4)

[0.47928661 0.71288906 0.41505346 0.37248109 0.59181637]


## randint()

In [12]:
var5 = np.random.randint(10, 100, 6) #from 10 till 100, choose 6 no.s

print (var5)

[93 72 99 15 52 63]
