# Random 

## rand()

In [1]:
import numpy as np

var = np.random.rand(9) #random no.s between 0 and 1
var1 = np.random.rand(3,4) #random no.s between 0 and 1

print (var)
print ()
print (var1)

[0.1503163  0.63551732 0.97889463 0.53276123 0.37781146 0.79518844
 0.45396262 0.88344127 0.78873674]

[[9.24204979e-01 6.71583117e-01 7.34978819e-02 2.54762906e-01]
 [1.67891751e-01 6.58367554e-01 3.10236075e-01 3.41552069e-01]
 [7.49830058e-01 5.90638988e-04 7.95416731e-01 8.39642720e-01]]


## randn()
prints the no.s close to 0 (negative values allowed too)

In [2]:
var2 = np.random.randn(5)
var3 = np.random.randn(3,4)

print (var2)
print ()
print (var3)

[ 0.63592516 -0.45294162 -0.66715538  0.47827739  0.58925594]

[[ 1.67415666  0.46417566  0.745895    0.09685514]
 [-1.52257627  0.95172689  0.58380417 -0.11136257]
 [-0.10813654  0.70847448  0.02886276  1.15141944]]


## ranf()

In [3]:
var4 = np.random.ranf(5)

print (var4)

[0.46681118 0.0699832  0.38611315 0.48918856 0.27037405]


## randint()

In [11]:
var5 = np.random.randint(1, 100, 50) #from 10 till 100, choose 6 no.s

print (var5)

[ 9 43 62 67 21 86 92 60  9 30 12  7 61 98 22 19 67 74 48 44 52 15  4 84
 88 55 25 28 79  9 55 67 22 39 99 84 69 56 43 90 98 51 97 80 47 80 68 84
  6 75]
