## np.min(x)
## np.max(x) 
## np.argmin(x) 
## np.sqrt(x) 
## np.sin(x) 
## np.cos(x) 
## np.cumsum(x)

In [1]:
import numpy as np


var1 = np.array([4, 2, 7, 9])
print ("min: ",np.min(var1))
print ("position of min: ",np.argmin(var1))
print ("min: ",np.max(var1))
print ("position of max: ",np.argmax(var1))

min:  2
position of min:  1
min:  9
position of max:  3


In [2]:
var2 = np.array([[5, 6, 8], [3, 6, 9]])

print (np.max(var2 , axis= 0)) #axis = 0 means column
print (np.max(var2 , axis= 1)) #axis = 1 means column
print (np.min(var2 , axis= 0))
print (np.min(var2 , axis= 1))

print (np.sqrt(var2)) #sqrt to find the sq root
print (np.sin(var2)) #sin to find the sin value of the values
print (np.cos(var2)) #cos to find the sin value of the values
 

[5 6 9]
[8 9]
[3 6 8]
[5 3]
[[2.23606798 2.44948974 2.82842712]
 [1.73205081 2.44948974 3.        ]]
[[-0.95892427 -0.2794155   0.98935825]
 [ 0.14112001 -0.2794155   0.41211849]]
[[ 0.28366219  0.96017029 -0.14550003]
 [-0.9899925   0.96017029 -0.91113026]]


In [3]:
var3 = np.array([1, 3, 5, 6, 9])

print (np.cumsum(var3)) 

[ 1  4  9 15 24]
