# Shape

In [3]:
import numpy as np

var = np.array([[4, 6, 7], [5, 6, 5]])

print (var.ndim)
print ()
print (var.shape)

2

(2, 3)


In [7]:
var2 = np.array([5, 6, 7], ndmin= 4)

print (var2.ndim)
print (var2)
print (var2.shape)

4
[[[[5 6 7]]]]
(1, 1, 1, 3)


# Reshape

In [18]:
var3 = np.array([4, 5, 6, 7, 7, 67, 87, 8, 90])
print (var3.ndim)

x1 = var3.reshape(3,3,1) #3*3*1 = 9 i.e. total no. of elements in the array
x2 = var3.reshape(3,3) #3*3 = 9
print (x1.ndim)
print (x2.ndim)
print ()
print (x1)
print (x2)

1
3
2

[[[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 7]
  [67]]

 [[87]
  [ 8]
  [90]]]
[[ 4  5  6]
 [ 7  7 67]
 [87  8 90]]


In [21]:
one = x2.reshape(-1)
print (x2)
print (x2.ndim)
print ()
print (one)

print (one.ndim)

[[ 4  5  6]
 [ 7  7 67]
 [87  8 90]]
2

[ 4  5  6  7  7 67 87  8 90]
1
